/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./components/scrollbar/src/bar.vue')['default']
    Chart: typeof import('./components/NtChart/Chart.vue')['default']
    EditCategoryDialog: typeof import('./components/dialog/EditCategoryDialog.vue')['default']
    EditSettingDialog: typeof import('./components/dialog/EditSettingDialog.vue')['default']
    HighLight: typeof import('./components/HighLight.vue')['default']
    NtAvatar: typeof import('./components/NtAvatar.vue')['default']
    NtButton: typeof import('./components/NtButton.vue')['default']
    NtCard: typeof import('./components/NtCard.vue')['default']
    NtChart: typeof import('./components/NtChart/NtChart.vue')['default']
    NtConfigProvide: typeof import('./components/NtConfigProvide.vue')['default']
    NtContent: typeof import('./components/Loyout/NtContent.vue')['default']
    NtDialog: typeof import('./components/dialog/NtDialog.vue')['default']
    NtDropdown: typeof import('./components/NtDropdown.vue')['default']
    NtEditor: typeof import('./components/NtEditor.vue')['default']
    NtEditorContent: typeof import('./components/NtEditorContent.vue')['default']
    NtHeader: typeof import('./components/NtHeader.vue')['default']
    NtIcon: typeof import('./components/NtIcon.vue')['default']
    NtIconButton: typeof import('./components/NtIconButton.vue')['default']
    NtInput: typeof import('./components/NtInput.vue')['default']
    NtLinkButton: typeof import('./components/NtLinkButton.vue')['default']
    NtMenus: typeof import('./components/NtMenus.vue')['default']
    NtMenusTitle: typeof import('./components/NtMenusTitle.vue')['default']
    NtProgress: typeof import('./components/NtProgress.vue')['default']
    NtScrollbar: typeof import('./components/scrollbar/src/NtScrollbar.vue')['default']
    NtSplit: typeof import('./components/NtSplit.vue')['default']
    NtStatistic: typeof import('./components/NtStatistic.vue')['default']
    NtTag: typeof import('./components/NtTag.vue')['default']
    NtTooltip: typeof import('./components/NtTooltip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/test/Test.vue')['default']
    Thumb: typeof import('./components/scrollbar/src/thumb.vue')['default']
  }
}
