/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NtConfigProvide: typeof import('./components/NtConfigProvide.vue')['default']
    NtEditor: typeof import('./components/NtEditor.vue')['default']
    NtIcon: typeof import('./components/NtIcon.vue')['default']
    NtMenus: typeof import('./components/NtMenus.vue')['default']
    NtMenusTitle: typeof import('./components/NtMenusTitle.vue')['default']
    NtNav: typeof import('./components/NtNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
