/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./components/scrollbar/src/bar.vue')['default']
    EditCategory: typeof import('./components/dialog/EditCategoryDialog.vue')['default']
    EditCategoryDialog: typeof import('./components/dialog/EditCategoryDialog.vue')['default']
    EditTAg: (typeof import('./components/dialog/EditCategoryDialog.vue'))['default']
    FyScrollbar: typeof import('./components/scrollbar/src/FyScrollbar.vue')['default']
    HighLight: typeof import('./components/HighLight.vue')['default']
    NtButton: typeof import('./components/NtButton.vue')['default']
    NtConfigProvide: typeof import('./components/NtConfigProvide.vue')['default']
    NtContent: typeof import('./components/Loyout/NtContent.vue')['default']
    NtDialog: typeof import('./components/dialog/NtDialog.vue')['default']
    NtEditor: typeof import('./components/NtEditor.vue')['default']
    NtHead: typeof import('./components/NtHeader.vue')['default']
    NtHeader: typeof import('./components/NtHeader.vue')['default']
    NtIcon: typeof import('./components/NtIcon.vue')['default']
    NtInput: typeof import('./components/NtInput.vue')['default']
    NtInput2: (typeof import('./components/NtInput2.vue'))['default']
    NtMenus: typeof import('./components/NtMenus.vue')['default']
    NtMenusTitle: typeof import('./components/NtMenusTitle.vue')['default']
    NtScrollbar: typeof import('./components/scrollbar/src/NtScrollbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Thumb: typeof import('./components/scrollbar/src/thumb.vue')['default']
  }
}
